// Mocks generated by Mockito 5.4.6 from annotations
// in multimesh/test/services/text_message/text_message_receiver_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:multimesh/models/mesh_node.dart' as _i12;
import 'package:multimesh/models/text_message.dart' as _i2;
import 'package:multimesh/models/text_message_status.dart' as _i5;
import 'package:multimesh/protobufs/generated/meshtastic/mesh.pb.dart' as _i6;
import 'package:multimesh/providers/node/node_service.dart' as _i9;
import 'package:multimesh/repository/text_message_repository.dart' as _i3;
import 'package:multimesh/services/interfaces/radio_reader.dart' as _i7;
import 'package:state_notifier/state_notifier.dart' as _i13;

import '../../common.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextMessage_0 extends _i1.SmartFake implements _i2.TextMessage {
  _FakeTextMessage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TextMessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextMessageRepository extends _i1.Mock
    implements _i3.TextMessageRepository {
  MockTextMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<List<_i2.TextMessage>>> getByNodeNum() => (super.noSuchMethod(
        Invocation.method(
          #getByNodeNum,
          [],
        ),
        returnValue: _i4.Future<List<List<_i2.TextMessage>>>.value(
            <List<_i2.TextMessage>>[]),
      ) as _i4.Future<List<List<_i2.TextMessage>>>);

  @override
  _i4.Future<int> add({required _i2.TextMessage? textMessage}) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {#textMessage: textMessage},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateStatusByPacketId({
    required _i5.TextMessageStatus? status,
    required int? packetId,
    _i6.Routing_Error? routingError = _i6.Routing_Error.NONE,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatusByPacketId,
          [],
          {
            #status: status,
            #packetId: packetId,
            #routingError: routingError,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.TextMessage> getByPacketId({required int? packetId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByPacketId,
          [],
          {#packetId: packetId},
        ),
        returnValue: _i4.Future<_i2.TextMessage>.value(_FakeTextMessage_0(
          this,
          Invocation.method(
            #getByPacketId,
            [],
            {#packetId: packetId},
          ),
        )),
      ) as _i4.Future<_i2.TextMessage>);

  @override
  _i4.Future<List<_i2.TextMessage>> getDirectMessagesBy({
    required int? myNodeNum,
    required int? otherNodeNum,
    required int? limit,
    int? offset = 0,
    required int? owner,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDirectMessagesBy,
          [],
          {
            #myNodeNum: myNodeNum,
            #otherNodeNum: otherNodeNum,
            #limit: limit,
            #offset: offset,
            #owner: owner,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.TextMessage>>.value(<_i2.TextMessage>[]),
      ) as _i4.Future<List<_i2.TextMessage>>);

  @override
  _i4.Future<List<_i2.TextMessage>> getBy({
    required int? toNode,
    required int? channel,
    required int? limit,
    int? offset = 0,
    required int? owner,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBy,
          [],
          {
            #toNode: toNode,
            #channel: channel,
            #limit: limit,
            #offset: offset,
            #owner: owner,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.TextMessage>>.value(<_i2.TextMessage>[]),
      ) as _i4.Future<List<_i2.TextMessage>>);

  @override
  _i4.Future<int> countDirectMessagesBy({
    required int? myNodeNum,
    required int? otherNodeNum,
    required int? owner,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #countDirectMessagesBy,
          [],
          {
            #myNodeNum: myNodeNum,
            #otherNodeNum: otherNodeNum,
            #owner: owner,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> count({
    required int? channel,
    required int? toNode,
    required int? owner,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
          {
            #channel: channel,
            #toNode: toNode,
            #owner: owner,
          },
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [RadioReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockRadioReader extends _i1.Mock implements _i7.RadioReader {
  MockRadioReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i6.FromRadio> onPacketReceived() => (super.noSuchMethod(
        Invocation.method(
          #onPacketReceived,
          [],
        ),
        returnValue: _i4.Stream<_i6.FromRadio>.empty(),
      ) as _i4.Stream<_i6.FromRadio>);
}

/// A class which mocks [ShowNotification].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowNotification extends _i1.Mock implements _i8.ShowNotification {
  MockShowNotification() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> showNotification({
    required String? title,
    required String? text,
    required String? callbackValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #title: title,
            #text: text,
            #callbackValue: callbackValue,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeService extends _i1.Mock implements _i9.NodeService {
  MockNodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Ref get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _i11.dummyValue<_i10.Ref>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i10.Ref);

  @override
  Map<int, _i12.MeshNode> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: <int, _i12.MeshNode>{},
      ) as Map<int, _i12.MeshNode>);

  @override
  set state(Map<int, _i12.MeshNode>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<int, _i12.MeshNode> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: <int, _i12.MeshNode>{},
      ) as Map<int, _i12.MeshNode>);

  @override
  void notifyHasUnreadMessages(int? nodeNum) => super.noSuchMethod(
        Invocation.method(
          #notifyHasUnreadMessages,
          [nodeNum],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsetHasUnreadMessages(int? nodeNum) => super.noSuchMethod(
        Invocation.method(
          #unsetHasUnreadMessages,
          [nodeNum],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void runBuild() => super.noSuchMethod(
        Invocation.method(
          #runBuild,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.RemoveListener listenSelf(
    void Function(
      Map<int, _i12.MeshNode>?,
      Map<int, _i12.MeshNode>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValue: () {},
      ) as _i13.RemoveListener);

  @override
  bool updateShouldNotify(
    Map<int, _i12.MeshNode>? previous,
    Map<int, _i12.MeshNode>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
      ) as bool);
}
