// Mocks generated by Mockito 5.4.6 from annotations
// in multimesh/test/services/radio_config/radio_config_uploader_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:multimesh/protobufs/generated/meshtastic/mesh.pb.dart' as _i5;
import 'package:multimesh/protobufs/generated/meshtastic/portnums.pb.dart'
    as _i4;
import 'package:multimesh/services/ack_waiting_radio_writer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AckWaitingRadioWriter].
///
/// See the documentation for Mockito's code generation for more information.
class MockAckWaitingRadioWriter extends _i1.Mock
    implements _i2.AckWaitingRadioWriter {
  MockAckWaitingRadioWriter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendMeshPacket({
    required int? to,
    int? channel = 0,
    bool? wantAck = false,
    required _i4.PortNum? portNum,
    _i5.MeshPacket_Priority? priority = _i5.MeshPacket_Priority.RELIABLE,
    bool? wantResponse,
    _i6.Uint8List? payload,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMeshPacket,
          [],
          {
            #to: to,
            #channel: channel,
            #wantAck: wantAck,
            #portNum: portNum,
            #priority: priority,
            #wantResponse: wantResponse,
            #payload: payload,
            #id: id,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendWantConfig({required int? wantConfigId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendWantConfig,
          [],
          {#wantConfigId: wantConfigId},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int generatePacketId() => (super.noSuchMethod(
        Invocation.method(
          #generatePacketId,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> waitForAck(int? packetId) => (super.noSuchMethod(
        Invocation.method(
          #waitForAck,
          [packetId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
