name: multimesh
description: "A cross-platform Meshtastic client based on Flutter"

publish_to: 'none'

version: 0.2.4+21

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  chat_bubbles: ^1.6.0
  convert: ^3.1.1
  crypto: ^3.0.3
  csv: ^6.0.0
  easy_debounce: ^2.0.3
  file_saver: ^0.3.1
  firebase_analytics: ^12.0.3
  firebase_core: ^4.2.0
  firebase_crashlytics: ^5.0.3
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.3.1
  flutter_foreground_task: ^9.1.0
  flutter_local_notifications: ^19.5.0
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.0.9
  freezed_annotation: ^3.1.0
  go_router: ^16.2.5
  http: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mobile_scanner: ^7.1.2
  mockito: ^5.4.4
  package_info_plus: ^9.0.0
  path: ^1.9.0
  permission_handler: ^12.0.1
  platform: ^3.1.4
  protobuf: ^2.1.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^3.0.3
  scrollview_observer: ^1.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/meshx.png"
  min_sdk_android: 21
  remove_alpha_ios: true
