// Mocks generated by Mockito 5.4.6 from annotations
// in multimesh/test/services/ble/ble_radio_writer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_reactive_ble/flutter_reactive_ble.dart' as _i3;
import 'package:flutter_reactive_ble/src/discovered_devices_registry.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:multimesh/models/ble_characteristics.dart' as _i4;
import 'package:multimesh/models/mesh_radio.dart' as _i5;
import 'package:multimesh/models/radio_connector_state.dart' as _i8;
import 'package:reactive_ble_platform_interface/reactive_ble_platform_interface.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDiscoveredDevicesRegistryImpl_0 extends _i1.SmartFake
    implements _i2.DiscoveredDevicesRegistryImpl {
  _FakeDiscoveredDevicesRegistryImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacteristic_1 extends _i1.SmartFake
    implements _i3.Characteristic {
  _FakeCharacteristic_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBleCharacteristics_2 extends _i1.SmartFake
    implements _i4.BleCharacteristics {
  _FakeBleCharacteristics_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBleMeshRadio_3 extends _i1.SmartFake implements _i5.BleMeshRadio {
  _FakeBleMeshRadio_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQualifiedCharacteristic_4 extends _i1.SmartFake
    implements _i6.QualifiedCharacteristic {
  _FakeQualifiedCharacteristic_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlutterReactiveBle].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterReactiveBle extends _i1.Mock
    implements _i3.FlutterReactiveBle {
  MockFlutterReactiveBle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DiscoveredDevicesRegistryImpl get scanRegistry => (super.noSuchMethod(
        Invocation.getter(#scanRegistry),
        returnValue: _FakeDiscoveredDevicesRegistryImpl_0(
          this,
          Invocation.getter(#scanRegistry),
        ),
      ) as _i2.DiscoveredDevicesRegistryImpl);

  @override
  _i7.Stream<_i6.BleStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i7.Stream<_i6.BleStatus>.empty(),
      ) as _i7.Stream<_i6.BleStatus>);

  @override
  _i6.BleStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i6.BleStatus.unknown,
      ) as _i6.BleStatus);

  @override
  _i7.Stream<_i6.ConnectionStateUpdate> get connectedDeviceStream =>
      (super.noSuchMethod(
        Invocation.getter(#connectedDeviceStream),
        returnValue: _i7.Stream<_i6.ConnectionStateUpdate>.empty(),
      ) as _i7.Stream<_i6.ConnectionStateUpdate>);

  @override
  _i7.Stream<_i6.CharacteristicValue> get characteristicValueStream =>
      (super.noSuchMethod(
        Invocation.getter(#characteristicValueStream),
        returnValue: _i7.Stream<_i6.CharacteristicValue>.empty(),
      ) as _i7.Stream<_i6.CharacteristicValue>);

  @override
  _i6.LogLevel get logLevel => (super.noSuchMethod(
        Invocation.getter(#logLevel),
        returnValue: _i6.LogLevel.none,
      ) as _i6.LogLevel);

  @override
  set logLevel(_i6.LogLevel? logLevel) => super.noSuchMethod(
        Invocation.setter(
          #logLevel,
          logLevel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deinitialize() => (super.noSuchMethod(
        Invocation.method(
          #deinitialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<int>> readCharacteristic(
          _i6.QualifiedCharacteristic? characteristic) =>
      (super.noSuchMethod(
        Invocation.method(
          #readCharacteristic,
          [characteristic],
        ),
        returnValue: _i7.Future<List<int>>.value(<int>[]),
      ) as _i7.Future<List<int>>);

  @override
  _i7.Future<void> writeCharacteristicWithResponse(
    _i6.QualifiedCharacteristic? characteristic, {
    required List<int>? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeCharacteristicWithResponse,
          [characteristic],
          {#value: value},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> writeCharacteristicWithoutResponse(
    _i6.QualifiedCharacteristic? characteristic, {
    required List<int>? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeCharacteristicWithoutResponse,
          [characteristic],
          {#value: value},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> requestMtu({
    required String? deviceId,
    required int? mtu,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestMtu,
          [],
          {
            #deviceId: deviceId,
            #mtu: mtu,
          },
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> requestConnectionPriority({
    required String? deviceId,
    required _i6.ConnectionPriority? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestConnectionPriority,
          [],
          {
            #deviceId: deviceId,
            #priority: priority,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Stream<_i6.DiscoveredDevice> scanForDevices({
    required List<_i6.Uuid>? withServices,
    _i6.ScanMode? scanMode = _i6.ScanMode.balanced,
    bool? requireLocationServicesEnabled = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanForDevices,
          [],
          {
            #withServices: withServices,
            #scanMode: scanMode,
            #requireLocationServicesEnabled: requireLocationServicesEnabled,
          },
        ),
        returnValue: _i7.Stream<_i6.DiscoveredDevice>.empty(),
      ) as _i7.Stream<_i6.DiscoveredDevice>);

  @override
  _i7.Stream<_i6.ConnectionStateUpdate> connectToDevice({
    required String? id,
    Map<_i6.Uuid, List<_i6.Uuid>>? servicesWithCharacteristicsToDiscover,
    Duration? connectionTimeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToDevice,
          [],
          {
            #id: id,
            #servicesWithCharacteristicsToDiscover:
                servicesWithCharacteristicsToDiscover,
            #connectionTimeout: connectionTimeout,
          },
        ),
        returnValue: _i7.Stream<_i6.ConnectionStateUpdate>.empty(),
      ) as _i7.Stream<_i6.ConnectionStateUpdate>);

  @override
  _i7.Stream<_i6.ConnectionStateUpdate> connectToAdvertisingDevice({
    required String? id,
    required List<_i6.Uuid>? withServices,
    required Duration? prescanDuration,
    Map<_i6.Uuid, List<_i6.Uuid>>? servicesWithCharacteristicsToDiscover,
    Duration? connectionTimeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToAdvertisingDevice,
          [],
          {
            #id: id,
            #withServices: withServices,
            #prescanDuration: prescanDuration,
            #servicesWithCharacteristicsToDiscover:
                servicesWithCharacteristicsToDiscover,
            #connectionTimeout: connectionTimeout,
          },
        ),
        returnValue: _i7.Stream<_i6.ConnectionStateUpdate>.empty(),
      ) as _i7.Stream<_i6.ConnectionStateUpdate>);

  @override
  _i7.Future<List<_i6.DiscoveredService>> discoverServices(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverServices,
          [deviceId],
        ),
        returnValue: _i7.Future<List<_i6.DiscoveredService>>.value(
            <_i6.DiscoveredService>[]),
      ) as _i7.Future<List<_i6.DiscoveredService>>);

  @override
  _i7.Future<void> discoverAllServices(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #discoverAllServices,
          [deviceId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Service>> getDiscoveredServices(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscoveredServices,
          [deviceId],
        ),
        returnValue: _i7.Future<List<_i3.Service>>.value(<_i3.Service>[]),
      ) as _i7.Future<List<_i3.Service>>);

  @override
  _i7.Future<void> clearGattCache(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #clearGattCache,
          [deviceId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> readRssi(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #readRssi,
          [deviceId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Stream<List<int>> subscribeToCharacteristic(
          _i6.QualifiedCharacteristic? characteristic) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToCharacteristic,
          [characteristic],
        ),
        returnValue: _i7.Stream<List<int>>.empty(),
      ) as _i7.Stream<List<int>>);

  @override
  _i7.Future<Iterable<_i3.Characteristic>> resolve(
          _i6.QualifiedCharacteristic? characteristic) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [characteristic],
        ),
        returnValue: _i7.Future<Iterable<_i3.Characteristic>>.value(
            <_i3.Characteristic>[]),
      ) as _i7.Future<Iterable<_i3.Characteristic>>);

  @override
  _i7.Future<_i3.Characteristic> resolveSingle(
          _i6.QualifiedCharacteristic? characteristic) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveSingle,
          [characteristic],
        ),
        returnValue: _i7.Future<_i3.Characteristic>.value(_FakeCharacteristic_1(
          this,
          Invocation.method(
            #resolveSingle,
            [characteristic],
          ),
        )),
      ) as _i7.Future<_i3.Characteristic>);
}

/// A class which mocks [BleConnected].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockBleConnected extends _i1.Mock implements _i8.BleConnected {
  MockBleConnected() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BleCharacteristics get bleCharacteristics => (super.noSuchMethod(
        Invocation.getter(#bleCharacteristics),
        returnValue: _FakeBleCharacteristics_2(
          this,
          Invocation.getter(#bleCharacteristics),
        ),
      ) as _i4.BleCharacteristics);

  @override
  bool get isNewRadio => (super.noSuchMethod(
        Invocation.getter(#isNewRadio),
        returnValue: false,
      ) as bool);

  @override
  _i5.BleMeshRadio get radio => (super.noSuchMethod(
        Invocation.getter(#radio),
        returnValue: _FakeBleMeshRadio_3(
          this,
          Invocation.getter(#radio),
        ),
      ) as _i5.BleMeshRadio);

  @override
  String get radioId => (super.noSuchMethod(
        Invocation.getter(#radioId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#radioId),
        ),
      ) as String);

  @override
  _i8.Connected<_i5.MeshRadio> copyWith({
    bool? isNewRadio,
    _i5.BleMeshRadio? radio,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #isNewRadio: isNewRadio,
            #radio: radio,
          },
        ),
        returnValue: _i9.dummyValue<_i8.Connected<_i5.MeshRadio>>(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #isNewRadio: isNewRadio,
              #radio: radio,
            },
          ),
        ),
      ) as _i8.Connected<_i5.MeshRadio>);
}

/// A class which mocks [BleCharacteristics].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleCharacteristics extends _i1.Mock
    implements _i4.BleCharacteristics {
  MockBleCharacteristics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.QualifiedCharacteristic get toRadio => (super.noSuchMethod(
        Invocation.getter(#toRadio),
        returnValue: _FakeQualifiedCharacteristic_4(
          this,
          Invocation.getter(#toRadio),
        ),
      ) as _i6.QualifiedCharacteristic);

  @override
  _i6.QualifiedCharacteristic get fromRadio => (super.noSuchMethod(
        Invocation.getter(#fromRadio),
        returnValue: _FakeQualifiedCharacteristic_4(
          this,
          Invocation.getter(#fromRadio),
        ),
      ) as _i6.QualifiedCharacteristic);

  @override
  _i6.QualifiedCharacteristic get fromNum => (super.noSuchMethod(
        Invocation.getter(#fromNum),
        returnValue: _FakeQualifiedCharacteristic_4(
          this,
          Invocation.getter(#fromNum),
        ),
      ) as _i6.QualifiedCharacteristic);
}
