// Mocks generated by Mockito 5.4.6 from annotations
// in multimesh/test/services/ble/ble_permissions_requester_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_reactive_ble/flutter_reactive_ble.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:multimesh/services/wrap/flutter_blue_plus_mockable.dart' as _i4;
import 'package:multimesh/services/wrap/permissions.dart' as _i7;
import 'package:platform/platform.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalPlatform].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalPlatform extends _i1.Mock implements _i2.LocalPlatform {
  MockLocalPlatform() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get numberOfProcessors => (super.noSuchMethod(
        Invocation.getter(#numberOfProcessors),
        returnValue: 0,
      ) as int);

  @override
  String get pathSeparator => (super.noSuchMethod(
        Invocation.getter(#pathSeparator),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#pathSeparator),
        ),
      ) as String);

  @override
  String get operatingSystem => (super.noSuchMethod(
        Invocation.getter(#operatingSystem),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#operatingSystem),
        ),
      ) as String);

  @override
  String get operatingSystemVersion => (super.noSuchMethod(
        Invocation.getter(#operatingSystemVersion),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#operatingSystemVersion),
        ),
      ) as String);

  @override
  String get localHostname => (super.noSuchMethod(
        Invocation.getter(#localHostname),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#localHostname),
        ),
      ) as String);

  @override
  Map<String, String> get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  String get executable => (super.noSuchMethod(
        Invocation.getter(#executable),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#executable),
        ),
      ) as String);

  @override
  String get resolvedExecutable => (super.noSuchMethod(
        Invocation.getter(#resolvedExecutable),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#resolvedExecutable),
        ),
      ) as String);

  @override
  Uri get script => (super.noSuchMethod(
        Invocation.getter(#script),
        returnValue: _FakeUri_0(
          this,
          Invocation.getter(#script),
        ),
      ) as Uri);

  @override
  List<String> get executableArguments => (super.noSuchMethod(
        Invocation.getter(#executableArguments),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  bool get stdinSupportsAnsi => (super.noSuchMethod(
        Invocation.getter(#stdinSupportsAnsi),
        returnValue: false,
      ) as bool);

  @override
  bool get stdoutSupportsAnsi => (super.noSuchMethod(
        Invocation.getter(#stdoutSupportsAnsi),
        returnValue: false,
      ) as bool);

  @override
  String get localeName => (super.noSuchMethod(
        Invocation.getter(#localeName),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#localeName),
        ),
      ) as String);

  @override
  bool get isLinux => (super.noSuchMethod(
        Invocation.getter(#isLinux),
        returnValue: false,
      ) as bool);

  @override
  bool get isMacOS => (super.noSuchMethod(
        Invocation.getter(#isMacOS),
        returnValue: false,
      ) as bool);

  @override
  bool get isWindows => (super.noSuchMethod(
        Invocation.getter(#isWindows),
        returnValue: false,
      ) as bool);

  @override
  bool get isAndroid => (super.noSuchMethod(
        Invocation.getter(#isAndroid),
        returnValue: false,
      ) as bool);

  @override
  bool get isIOS => (super.noSuchMethod(
        Invocation.getter(#isIOS),
        returnValue: false,
      ) as bool);

  @override
  bool get isFuchsia => (super.noSuchMethod(
        Invocation.getter(#isFuchsia),
        returnValue: false,
      ) as bool);

  @override
  String toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #toJson,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [FlutterBluePlusMockable].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterBluePlusMockable extends _i1.Mock
    implements _i4.FlutterBluePlusMockable {
  MockFlutterBluePlusMockable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i6.BleStatus> get adapterState => (super.noSuchMethod(
        Invocation.getter(#adapterState),
        returnValue: _i5.Stream<_i6.BleStatus>.empty(),
      ) as _i5.Stream<_i6.BleStatus>);

  @override
  _i5.Stream<List<_i6.DiscoveredDevice>> get scanResults => (super.noSuchMethod(
        Invocation.getter(#scanResults),
        returnValue: _i5.Stream<List<_i6.DiscoveredDevice>>.empty(),
      ) as _i5.Stream<List<_i6.DiscoveredDevice>>);

  @override
  bool get isScanningNow => (super.noSuchMethod(
        Invocation.getter(#isScanningNow),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<bool> get isScanning => (super.noSuchMethod(
        Invocation.getter(#isScanning),
        returnValue: _i5.Stream<bool>.empty(),
      ) as _i5.Stream<bool>);

  @override
  _i5.Future<bool> get isSupported => (super.noSuchMethod(
        Invocation.getter(#isSupported),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String> get adapterName => (super.noSuchMethod(
        Invocation.getter(#adapterName),
        returnValue: _i5.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.getter(#adapterName),
        )),
      ) as _i5.Future<String>);

  @override
  List<String> get connectedDevices => (super.noSuchMethod(
        Invocation.getter(#connectedDevices),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<List<_i6.DiscoveredDevice>> get systemDevices =>
      (super.noSuchMethod(
        Invocation.getter(#systemDevices),
        returnValue: _i5.Future<List<_i6.DiscoveredDevice>>.value(
            <_i6.DiscoveredDevice>[]),
      ) as _i5.Future<List<_i6.DiscoveredDevice>>);

  @override
  _i5.Future<List<String>> get bondedDevices => (super.noSuchMethod(
        Invocation.getter(#bondedDevices),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> startScan({
    List<_i6.Uuid>? withServices = const [],
    Duration? timeout,
    Duration? removeIfGone,
    bool? oneByOne = false,
    bool? androidUsesFineLocation = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startScan,
          [],
          {
            #withServices: withServices,
            #timeout: timeout,
            #removeIfGone: removeIfGone,
            #oneByOne: oneByOne,
            #androidUsesFineLocation: androidUsesFineLocation,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopScan() => (super.noSuchMethod(
        Invocation.method(
          #stopScan,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i6.ConnectionStateUpdate> connectToDevice({
    required String? id,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToDevice,
          [],
          {
            #id: id,
            #timeout: timeout,
          },
        ),
        returnValue: _i5.Stream<_i6.ConnectionStateUpdate>.empty(),
      ) as _i5.Stream<_i6.ConnectionStateUpdate>);

  @override
  _i5.Future<void> disconnectDevice(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #disconnectDevice,
          [deviceId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.DiscoveredService>> discoverServices(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverServices,
          [deviceId],
        ),
        returnValue: _i5.Future<List<_i6.DiscoveredService>>.value(
            <_i6.DiscoveredService>[]),
      ) as _i5.Future<List<_i6.DiscoveredService>>);

  @override
  _i5.Stream<List<int>> subscribeToCharacteristic(
          _i6.QualifiedCharacteristic? characteristic) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToCharacteristic,
          [characteristic],
        ),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);

  @override
  _i5.Future<void> writeCharacteristicWithResponse(
    _i6.QualifiedCharacteristic? characteristic,
    List<int>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeCharacteristicWithResponse,
          [
            characteristic,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> writeCharacteristicWithoutResponse(
    _i6.QualifiedCharacteristic? characteristic,
    List<int>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeCharacteristicWithoutResponse,
          [
            characteristic,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<int>> readCharacteristic(
          _i6.QualifiedCharacteristic? characteristic) =>
      (super.noSuchMethod(
        Invocation.method(
          #readCharacteristic,
          [characteristic],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<void> turnOn({int? timeout = 60}) => (super.noSuchMethod(
        Invocation.method(
          #turnOn,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void cancelWhenScanComplete(
          _i5.StreamSubscription<List<_i6.DiscoveredDevice>>? subscription) =>
      super.noSuchMethod(
        Invocation.method(
          #cancelWhenScanComplete,
          [subscription],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Permissions].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissions extends _i1.Mock implements _i7.Permissions {
  MockPermissions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> locationWhenInUseRequest() => (super.noSuchMethod(
        Invocation.method(
          #locationWhenInUseRequest,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
